### ISSUE TITLE
OpenCL Error OSX Radeon HD6750

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire-ml#23]
jason@tesla ~/p/a/build> ./test/Activations_opencl
in[0] [5 1 1 1]
   -8.9262
   32.2371
   45.1800
  -32.0635
   -8.0176

libc++abi.dylib: terminating with uncaught exception of type af::exception: ArrayFire Exception(401): Double precision not supported for this device
In /var/lib/jenkins-slave/workspace/arrayfire-osx-graphics-installer/src/api/cpp/data.cpp:27
fish: Job 1, './test/Activations_opencl ' terminated by signal SIGABRT (Abort)

**Comment by jramapuram** [comment]
Are we trying to use double precision? Shouldn't be needed for nnets. The trajectory seems to be going to smaller and smaller types actually (i.e. nirvana's 16bit ultra fast impl)

**Comment by pavanky** [comment]
It should not be using double precision. Which version of ArrayFire are you using ?

**Comment by jramapuram** [comment]
3.02

**Comment by pavanky** [comment]
~~Can you try this with our devel branch ?~~

**Comment by pavanky** [comment]
This seems to be a problem in the main arrayfire library. I [pushed a fix](https://github.com/arrayfire/arrayfire-ml/commit/214c3777b44c21963bc38f3825b0b0f1f3ce398f) to this library that works around the issue.

**Comment by jramapuram** [comment]
Nice, ty Ill try it with the tip
