### ISSUE TITLE
Add Initializers

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire-ml#24]
Currently Nodes are defined to have spreads:

``` c++
            LinearNode(const int inputSize, const int outputSize,
                       float spread = 0.05,
                       const char *name="none") :
```

This needs to be refactored to provide an initializations class. 
Examples of initializations are : 
1. Le-Cun Normal
2. Glorot Uniform

**Comment by pavanky** [comment]
Erm.. Googling these terms seems to produce a lot of noise. Can you link to proper documentation ?

**Comment by jramapuram** [comment]
Yea, sorry. Keras has some links to the papers as well as the implementations:
https://github.com/fchollet/keras/blob/master/keras/initializations.py

**Comment by pavanky** [comment]
This can be implemented by adding a few functions in `Types.hpp`.

We'll need to implement the following:

- [x] The current `nn.weight` should be renamed to `nn.randomUniform`.
- [x] `nn.randomNormal` for normal
- [x] `nn.constant` similar to af::constant
- [x] `nn.identity`
- [x] `nn.lecunNormal`
- [x] `nn.lecunUniform`
- [x] `nn.glorotNormal`
- [x] `nn.glorotUniform`

The links for lecun* and glorot* can be found here:
https://github.com/fchollet/keras/blob/master/keras/initializers.py
