### ISSUE TITLE
Autodiff

### ISSUE THREAD

**Issue by botev** [arrayfire/arrayfire-ml#28]
Hi guys,

I've seen a lot of things in terms of ML frameworks, however for my work as a research I find autodiff very usefull (e.g. symbolic graph manipulation). On the other hand arrayfire seems like the perfect the backend for such framework, as it seemsly can be adopted for GPUs and so on (I'm still interested if there is any chance of adding somehow fallback to cuDNN where possible).

Since I've atempted such things, and however lack the experience of well written performance code, was wondering how open are you guys to such proposal and would anyone be interested in giving help for making better code generation to arrayfire.

I understand this is not your main goal, but I find arrayfire probably as best candidate for a computational backend, while autodiff gives a few orders of magnititude productivity. If I happen to this I do intend to do it in c++.

**Comment by pavanky** [comment]
@Botev We already have an issue open for this: https://github.com/arrayfire/arrayfire-ml/issues/2 

Can you make your suggestions and link any technical papers over there?
