### ISSUE TITLE
Is ML project dead?

### ISSUE THREAD

**Issue by FuriouslyCurious** [arrayfire/arrayfire-ml#29]
Didn't see any updates in a while, so wondering if ArrayFire ML project is still ongoing or abandoned.

Ideally would be great to have a "drop in" replacement for cuDNN used by Torch.

**Comment by pavanky** [comment]
> Didn't see any updates in a while, so wondering if ArrayFire ML project is still ongoing or abandoned.

I have been intending to do some work on this, but any planning I do comes up with having to do a bit of work upstream to have more building blocks (such as strided convolutions, pooling) etc. Once v3.4.0 is released, it should free up more resources from our end to work on this.

> Ideally would be great to have a "drop in" replacement for cuDNN used by Torch.

That is not our goal. But someone from the community can create a bridge for torch and have it be a drop in replacement for "torch.cunn".

**Comment by ghost** [comment]
Hello; in the mean-time, is there a document laying out which features are pretty stable and good for use, and which are somewhat unstable and dangerous to rely on? :)

Thank!
